# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.x'
    checkLatest: true
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: 'super-service/test/*[Tt]ests.csproj'
    arguments: '--configuration Release'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      docker build --tag superservice:latest .
      #docker run superservice:latest 
      #netstat -anpe | grep "3000" | grep "LISTEN"
    pwsh: true
    workingDirectory: '$(Build.SourcesDirectory)/super-service/src'